// apps/vue-ex/src/components/examples/ReRenders.vue
<script setup lang="ts">
import { ref } from 'vue'
import RandomChild from './RandomChild.vue'

const count = ref(0)

console.log('ReRendersExample rendered')
</script>

<template>
  <div class="flex flex-col gap-4 items-start">
    <h2 class="text-lg font-bold">Current count: {{ count }}</h2>
    <button
      class="bg-blue-500 text-white p-2 rounded-md"
      @click="count++"
    >
      Increment
    </button>
    <RandomChild />
  </div>
</template>

// apps/svelte-ex/src/lib/components/examples/ReRenders.svelte
<script lang="ts">
	import RandomChild from './RandomChild.svelte';

	let count = $state(0);

	console.log('ReRendersExample rendered');
</script>

<div class="flex flex-col gap-4 items-start">
	<h2 class="text-lg font-bold">Current count: {count}</h2>
	<button class="bg-blue-500 text-white p-2 rounded-md" onclick={() => count++}> Increment </button>
	<RandomChild />
</div>
