// apps/solid-ex/public/src/App.tsx
import type { Component } from "solid-js";
import { SolidLogo } from "./components/SolidLogo";

const App: Component = () => {
  return (
    <div class="w-full h-screen bg-neutral-900 text-white border-2 border-[#1B336A]">
      <header class="p-12 flex flex-row items-center justify-start gap-4">
        <SolidLogo class="size-24" />
        <h2 class="text-2xl font-bold">Solid Example</h2>
      </header>
    </div>
  );
};

export default App;

// apps/react-ex/src/App.tsx
import { ReactLogo } from "./components/ReactLogo";

function App() {
  return (
    <div className="w-full h-screen bg-neutral-900 text-white border-2 border-[#59C4DC]">
      <header className="p-12 flex flex-row items-center justify-start gap-4">
        <ReactLogo className="size-24" />
        <h2 className="text-2xl font-bold">React Example</h2>
      </header>
    </div>
  );
}

export default App;
